config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "tops#index"
  resources :users, :user_profiles do
    resources :user_comments, only: %i[create destroy]
  end
  resources :artisan_profiles, only: %i[index show edit update]
  resources :sessions, only: %i[new create destroy]
  resources :project_likes, only: %i[index create destroy]
  resources :relationships, only: %i[index create destroy]
  resources :ideas do
    resources :idea_comments, only: %i[create destroy]
    resources :conversations do
      resources :messages
    end
  end
  post 'projects/:id', to: 'project_returns#create'
  resources :projects do
    resources :comments, only: %i[create destroy]
  end
  # resources :conversations do
  #   resources :messages
  # end
  get 'agreements/terms_of_service'
  get 'agreements/privacy_policy'
  get 'agreements/product_team'
  resources :sponsor_lists, only: [:create]
  resources :coming_soons, only: [:index]
end

app/models/artisan_talkroom.rb
class ArtisanTalkroom < ApplicationRecord
end

app/controllers/artisan_talkrooms_controller.rb
class ArtisanTalkroomsController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_profile = @user.user_profile
    @artisan_profile = @user.artisan_profile
  end
  
  private

  def user_edit_params
    params.require(:user).permit(
      :name,
      :email,
      :image_name,
      :image_cache,
      :user_status,
      user_profile_attributes:[
        :id,
        :user_id,
        :family_name,
        :family_name_sub,
        :last_name,
        :last_name_sub,
        :sex,
        :birthday,
        :add_no,
        :prefectures,
        :address,
        :phone_no1,
        :phone_no2
      ],
      artisan_profile_attributes:[
        :id,
        :user_id,
        :workexp,
        :homeworkexp,
        :skill,
        :skill_free,
        :skill_exp,
        :genre_free,
        :item,
        :item_free,
        :facillity,
        :facillity_free,
        :workexp_text,
        :mypr,
        :myprofile,
        :work_status,
        artisan_genre_list_ids: [],
        artisan_item_list_ids: [],
        artisan_facillity_list_ids: [],
        artisan_processing_list_ids: []
      ]
    )
  end
end

app/helpers/artisan_talkrooms_helper.rb
module ArtisanTalkroomsHelper
end

app/views/artisan_talkrooms/show.html.erb
<main class="show-artisan-page">
  <h1 class="show-artisan-page__title">職人紹介&emsp;<%= link_to "職人一覧(仮置き)", artisan_profiles_path %></h1>
  <div class="row show-artisan1">
    <div class="col-md-4">
      <div class="col-md-8 show-artisan1__image__wrap">
        <span class="show-artisan1__image__decoration"><%= @artisan_profile.workexp %>年</span>
        <p class="show-artisan1__image">職人画像</p>
      </div>
    </div>

    <div class="col-md-7 show-artisan1__wrap">
      <div class="row show-artisan1__content__wrap">
        <p class="col-md-2"></p>
        <div class="col-md-10">
          <p class="show-artisan1__content"><%= @user_profile.family_name_sub %>　<%= @user_profile.last_name_sub %></p>
        </div>
      </div>

      <div class="row show-artisan1__content__wrap2">
        <p class="col-md-2 show-artisan1__title">名&emsp;前</p>
        <div class="col-md-10">
          <p class="show-artisan1__content2"><%= @user_profile.family_name %>　<%= @user_profile.last_name %></p>
        </div>
      </div>

      <div class="row show-artisan1__content__wrap3">
        <p class="col-md-2 show-artisan1__title">ジャンル</p>
        <div class="col-md-10">
          <% 2.times do %>
            <p class="col-md-2 show-artisan1__content3">レディース</p>
          <% end %>
        </div>
      </div>

      <div class="row show-artisan1__content__wrap3">
        <p class="col-md-2 show-artisan1__title">設備</p>
        <div class="col-md-10">
          <% 3.times do %>
            <p class="col-md-3 show-artisan1__content3">4本糸ロックミシン</p>
          <% end %>
        </div>
      </div>

      <div class="row show-artisan1__content__wrap3">
        <p class="col-md-2 show-artisan1__title">アイテム</p>
        <div class="col-md-10">
          <% 10.times do %>
            <p class="col-md-2 show-artisan1__content3">ジャケット</p>
          <% end %>
        </div>
      </div>

      <div class="row show-artisan1__content__wrap3">
        <p class="col-md-2 show-artisan1__title">スキル</p>
        <div class="col-md-10">
          <p class="col-md-2 show-artisan1__content3 show-artisan1__content4">スキル</p>
          <p class="col-md-2 show-artisan1__content5">スキル年数</p>
          <p class="col-md-2 show-artisan1__content3 show-artisan1__content4">10年</p>
        </div>
      </div>

      <div class="row show-artisan1__content__wrap3">
        <p class="col-md-2"></p>
        <div class="col-md-10">
          <p class="col-md-10 show-artisan1__content6">スキル</p>
        </div>
      </div>

    </div>
  </div>

  <div class="row show-artisan2">
    
  </div>

</main>