config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "tops#index"
  resources :users, :user_profiles do
    resources :user_comments, only: %i[create destroy]
  end
  resources :artisan_profiles, only: %i[index show edit update]
  resources :sessions, only: %i[new create destroy]
  resources :project_likes, only: %i[index create destroy]
  resources :relationships, only: %i[index create destroy]
  resources :ideas do
    resources :idea_comments, only: %i[create destroy]
    resources :conversations do
      resources :messages
    end
  end
  post 'projects/:id', to: 'project_returns#create'
  resources :projects do
    resources :comments, only: %i[create destroy]
  end
  # resources :conversations do
  #   resources :messages
  # end
  get 'agreements/terms_of_service'
  get 'agreements/privacy_policy'
  get 'agreements/product_team'
  resources :sponsor_lists, only: [:create]
  resources :coming_soons, only: [:index]
end

app/models/artisan_profile.rb
class ArtisanProfile < ApplicationRecord
  has_many :select_genre_in_artisans, inverse_of: :artisan_profile, dependent: :destroy
  has_many :artisan_genre_lists, through: :select_genre_in_artisans
  has_many :select_item_in_artisans, inverse_of: :artisan_profile, dependent: :destroy
  has_many :artisan_item_lists, through: :select_item_in_artisans
  has_many :select_facillity_in_artisans, inverse_of: :artisan_profile, dependent: :destroy
  has_many :artisan_facillity_lists, through: :select_facillity_in_artisans
  has_many :select_processing_in_artisans, inverse_of: :artisan_profile, dependent: :destroy
  has_many :artisan_processing_lists, through: :select_processing_in_artisans

  belongs_to :user, inverse_of: :artisan_profile
end

app/controllers/artisan_profiles_controller.rb
class ArtisanProfilesController < ApplicationController
  before_action :require_login
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :artisan_profile_authority, only: [:edit, :update]

  def index
    @artisans = User.where(user_status: 2 )
  end

  def show
    if @user.user_status == 2
      @user_profile = @user.user_profile #userのログイン名とメルアド以外が格納
      @artisan_profile = @user.artisan_profile #職人情報が格納
      @artisan_genres = @artisan_profile.artisan_genre_lists.pluck(:genre_name)# ジャンル
      @artisan_facillities = @artisan_profile.artisan_facillity_lists.pluck(:facillity_name)# 設備
      @artisan_items = @artisan_profile.artisan_item_lists.pluck(:item_name)# アイテム
    else
      redirect_to root_path, alert: "職人登録をしてください。"
    end
  end

  def edit
    @user_profile = @user.user_profile
    @artisan_profile = @user.artisan_profile
  end

  def update
    if @user.update(user_edit_params)
      redirect_to artisan_profile_path(@user.id), notice: "プロフィールを更新しました。"
    else
      flash.now[:alert] = "プロフィールを修正できませんでした。"
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_edit_params
    params.require(:user).permit(
      :name,
      :email,
      :image_name,
      :image_cache,
      :user_status,
      user_profile_attributes:[
        :id,
        :user_id,
        :family_name,
        :family_name_sub,
        :last_name,
        :last_name_sub,
        :sex,
        :birthday,
        :add_no,
        :prefectures,
        :address,
        :phone_no1,
        :phone_no2
      ],
      artisan_profile_attributes:[
        :id,
        :user_id,
        :workexp,
        :homeworkexp,
        :skill,
        :skill_free,
        :skill_exp,
        :genre_free,
        :item,
        :item_free,
        :facillity,
        :facillity_free,
        :workexp_text,
        :mypr,
        :myprofile,
        :work_status,
        artisan_genre_list_ids: [],
        artisan_item_list_ids: [],
        artisan_facillity_list_ids: [],
        artisan_processing_list_ids: []
      ]
    )
  end

  def artisan_profile_authority
    if @user.id != current_user.id
      redirect_to root_path, alert: "権限がありません。"
    end
  end
end

app/helpers/artisan_profiles_helper.rb
module ArtisanProfilesHelper
end

app/views/artisan_profiles/_edit.html.erb
<div class="container">
  <div class="py-5 text-center">
    <h2></h2>
    <p class="lead"></p>
  </div>
  <%= form_with(model: @artisan_profile, url: artisan_profile_path, local: true, method: :patch) do |f| %>
    <div class="row">
      <div class="col-md-4 order-md-1 mb-4">
        <strong>Image:</strong>
        <%= image_tag @user.image.to_s %>
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted"><%= @user.name %></span>
        </h4>
        <ul class="list-group mb-3">
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">アイディア一覧</h6>
              <small class="text-muted">投稿したアイディアの管理</small>
            </div>
            <span class="text-muted"></span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">メッセージ一覧</h6>
              <small class="text-muted">メッセージはこまめにCheck！</small>
            </div>
            <span class="text-muted"></span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">お支払い・売り上げ管理</h6>
              <small class="text-muted">口座登録・振り込み申請などもコチラ</small>
            </div>
            <span class="text-muted"></span>
          </li>
          <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">会員情報・変更</h6>
              <small>EXAMPLECODE</small>
            </div>
            <span class="text-success"></span>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <span></span>
            <strong></strong>
          </li>
        </ul>
      </div>

      <div class="col-md-8 order-md-2">
        <%= f.fields_for :user_profile do |a| %>
          <h4 class="mb-3">プロフィール</h4>
          
          <div class="row">
            <div class="col-md-6 mb-3">
              <%= a.label :family_name %>
              <%= a.text_field :family_name, class: "form-control", id: "firstName", placeholder: "例）山田", value: @user.user_profile.family_name %>

              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <label for="lastName">Last name</label>
              <%= a.text_field :last_name, class: "form-control", id: "lastName", placeholder: "例）太郎", value: @user.user_profile.last_name  %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <label for="firstNameSub">First name</label>
              <%= a.text_field :family_name_sub, class: "form-control", id: "firstName", placeholder: "例）やまだ", value: @user.user_profile.family_name_sub %>

              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <label for="lastName">Last name</label>
              <%= a.text_field :last_name_sub, class: "form-control", id: "lastName", placeholder: "例）たろう", value: @user.user_profile.last_name_sub  %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <%= a.label :add_no %>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">〒</span>
                </div>
                <%= a.text_field :add_no, class: "form-control", id: "AddNumber", placeholder: "例）0000000（ハイフン不要）" %>
                <div class="invalid-feedback" style="width: 100%;">
                  Your username is required.
                </div>
              </div>
            </div>
                          
            <div class="col-md-6 mb-3">
              <%= a.label :prefectures %>
              <%= a.text_field :prefectures, class: "form-control", id: "Prefectures", placeholder: "例）東京都" %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>

          <div class="mb-3">
            <%= a.label :address %>
            <%= a.text_field :address, class: "form-control", id: "address", placeholder: "建物名までご記入ください" %>
            <div class="invalid-feedback">
              Please enter your shipping address.
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <%= a.label :phone_no1 %>
              <%= a.text_field :phone_no1, class: "form-control", id: "PhoneNumber1", placeholder: "例）00000000000(ハイフン不要)" %>
              <div class="invalid-feedback" style="width: 100%;">
                Your username is required.
              </div>
            </div>
                          
            <div class="col-md-6 mb-3">
              <%= a.label :phone_no2 %>
              <%= a.text_field :phone_no2, class: "form-control", id: "PhoneNumber2", placeholder: "例）00000000000(ハイフン不要)" %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>
        <% end %>
      
        
        <h4 class="mb-3">職人プロフィール</h4>
          <%= f.fields_for :artisan_profile do |b| %>
          
          <div class="row">
            <div class="col-md-6 mb-3">
              <%= b.label :workexp %>
              <%= b.text_field :workexp, class: "form-control", id: "workExp", placeholder: "", value: @user.artisan_profile.workexp %>

              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <%= b.label :homeworkexp %>
              <%= b.text_field :homeworkexp, class: "form-control", id: "homeworkExp", placeholder: "", value: @user.artisan_profile.workexp  %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
            <%= b.label :skill %>
              <%= b.text_field :skill, class: "form-control", id: "skill", placeholder: "" %>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <label for="lastName">skill_free</label>
              <%= b.text_field :skill_free, class: "form-control", id: "skillFree", placeholder: ""  %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <%= b.label :skill_exp %>
              <%= b.text_field :skill_exp, class: "form-control", id: "skillExp", placeholder: "" %>
                <div class="invalid-feedback" style="width: 100%;">
                  Your username is required.
                </div>
            </div>
                          
            <div class="col-md-6 mb-3">
              <%= b.label :genre %>
              <%= b.text_field :genre, class: "form-control", id: "genre", placeholder: "" %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>

          <div class="mb-3">
            <%= b.label :genre_free %>
            <%= b.text_field :genre_free, class: "form-control", id: "genre_free", placeholder: "" %>
            <div class="invalid-feedback">
              Please enter your shipping address.
            </div>
          </div>
          <div class="mb-3">
          <%= f.submit :"職人プロフィールを編集する", class: "btn btn-primary btn-lg btn-block mt-5" %>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/artisan_profiles/_read.html.erb
<main class="container-fluid">
  <h1 class="row col-12 col-lg-10 my-page__title">職人情報</h1>

  <section>
    <%= form_with(model: @user, url: artisan_profile_path, local: true, method: :patch) do |f| %>
      <div class="row">

        <div class="col-md-8 order-md-2">
          <%= f.fields_for :user_profile do |a| %>
            <h4 class="mb-3">プロフィール</h4>

            <div class="row">
              <div class="col-md-6 mb-3">
                <%= a.label :family_name %>
                <%= a.text_field :family_name, class: "form-control", id: "firstName", placeholder: "例）山田", value: @user.user_profile.family_name, readonly: true %>
              </div>
              <div class="col-md-6 mb-3">
                <label for="lastName">Last name</label>
                <%= a.text_field :last_name, class: "form-control", id: "lastName", placeholder: "例）太郎", value: @user.user_profile.last_name, readonly: true %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="firstNameSub">First name</label>
                <%= a.text_field :family_name_sub, class: "form-control", id: "firstName", placeholder: "例）やまだ", value: @user.user_profile.family_name_sub, readonly: true %>
              </div>
              <div class="col-md-6 mb-3">
                <label for="lastName">Last name</label>
                <%= a.text_field :last_name_sub, class: "form-control", id: "lastName", placeholder: "例）たろう", value: @user.user_profile.last_name_sub, readonly: true  %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6 mb-3">
                <%= a.label :add_no %>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">〒</span>
                  </div>
                  <%= a.text_field :add_no, class: "form-control", id: "AddNumber", placeholder: "例）0000000（ハイフン不要）", readonly: true %>
                </div>
              </div>

              <div class="col-md-6 mb-3">
                <%= a.label :prefectures %>
                <%= a.text_field :prefectures, class: "form-control", id: "Prefectures", placeholder: "例）東京都", readonly: true %>
              </div>
            </div>

            <div class="mb-3">
              <%= a.label :address %>
              <%= a.text_field :address, class: "form-control", id: "address", placeholder: "建物名までご記入ください", readonly: true %>
            </div>

            <div class="row">
              <div class="col-md-6 mb-3">
                <%= a.label :phone_no1 %>
                <%= a.text_field :phone_no1, class: "form-control", id: "PhoneNumber1", placeholder: "例）00000000000(ハイフン不要)", readonly: true %>
              </div>

              <div class="col-md-6 mb-3">
                <%= a.label :phone_no2 %>
                <%= a.text_field :phone_no2, class: "form-control", id: "PhoneNumber2", placeholder: "例）00000000000(ハイフン不要)", readonly: true %>
              </div>
            </div>
          <% end %>

          <h4 class="mb-3">職人プロフィール</h4>
            <%= f.fields_for :artisan_profile do |b| %>

              <div class="row">
                <div class="col-md-6 mb-3">
                  <%= b.label :workexp %>
                  <%= b.text_field :workexp, class: "form-control", id: "workExp", placeholder: "", value: @user.artisan_profile.workexp, readonly: true %>
                </div>
                <div class="col-md-6 mb-3">
                  <%= b.label :homeworkexp %>
                  <%= b.text_field :homeworkexp, class: "form-control", id: "homeworkExp", placeholder: "", value: @user.artisan_profile.homeworkexp, readonly: true  %>
                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-3">
                <%= b.label :skill %>
                  <%= b.text_field :skill, class: "form-control", id: "skill", placeholder: "", readonly: true %>
                </div>
                <div class="col-md-6 mb-3">
                  <label for="lastName">skill_free</label>
                  <%= b.text_field :skill_free, class: "form-control", id: "skillFree", placeholder: "" , readonly: true %>
                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-3">
                  <%= b.label :skill_exp %>
                  <%= b.text_field :skill_exp, class: "form-control", id: "skillExp", placeholder: "", readonly: true %>
                </div>
              </div>

              <div class="mb-3">
                  <%= b.label :genre %>
                  <div class="field">
                    <% ArtisanGenreList.all.each do |genreList| %>
                      <%= b.check_box :artisan_genre_list_ids, { multiple: true, checked: @artisan_profile.artisan_genre_lists.find_by(id: genreList.id)
                          .present?, include_hidden: false }, genreList[:id] %>
                      <%= genreList.genre_name %>
                    <% end %>
                  </div>
              </div>

              <div class="mb-3">
                <%= b.label :genre_free %>
                <%= b.text_field :genre_free, class: "form-control", id: "genre_free", placeholder: "", readonly: true %>
              </div>

              <div class="mb-3">
                <%= b.label :item %>
                <div class="field">
                  <% ArtisanItemList.all.each do |itemList| %>
                    <%= b.check_box :artisan_item_list_ids, { multiple: true, checked: @artisan_profile.artisan_item_lists.find_by(id: itemList.id)
                        .present?, include_hidden: false }, itemList[:id] %>
                    <%= itemList.item_name %>
                  <% end %>
                </div>
              </div>

              <div class="mb-3">
                <%= b.label :item_free %>
                <%= b.text_field :item_free, class: "form-control", id: "item_free", placeholder: "", readonly: true %>
              </div>

              <div class="mb-3">
              <%= b.label :facillity %>
              <div class="field">
                <% ArtisanFacillityList.all.each do |facillityList| %>
                  <%= b.check_box :artisan_facillity_list_ids, { multiple: true, checked: @artisan_profile.artisan_facillity_lists.find_by(id: facillityList.id)
                      .present?, include_hidden: false }, facillityList[:id] %>
                  <%= facillityList.facillity_name %>
                <% end %>
              </div>

              <div class="mb-3">
                <%= b.label :facillity_free %>
                <%= b.text_field :facillity_free, class: "form-control", id: "facillity_free", placeholder: "", readonly: true %>
              </div>

              <div class="mb-3">
                <%= b.label :workexp_text %>
                <%= b.text_field :workexp_text, class: "form-control", id: "workexp_text", placeholder: "", readonly: true %>
              </div>

              <div class="mb-3">
                <%= b.label :mypr %>
                <%= b.text_field :mypr, class: "form-control", id: "mypr", placeholder: "", readonly: true %>
              </div>

              <div class="mb-3">
                <%= b.label :myprofile %>
                <%= b.text_field :myprofile, class: "form-control", id: "myprofile", placeholder: "", readonly: true %>
              </div>

              <div class="mb-3">
                <%= b.label :work_status %>
                <%= b.text_field :work_status, class: "form-control", id: "work_status", placeholder: "", readonly: true %>
              </div>

              <div class="mb-3">
                <%= link_to "職人プロフィールを編集画面", edit_artisan_profile_path(current_user.id), class: "btn btn-primary btn-lg btn-block mt-5" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </section>
</main>

app/views/artisan_profiles/_show.html.erb
<div class="container">
  <p>
  <strong>Image:</strong>
  <%= image_tag @user.image.to_s %>
  </p>
  <h1>user詳細画面</h1>
  <p>ニックネーム：<%= @user.name %></p>
  <p>登録メール：<%= @user.email %></p>
  
  <p>ふりがな：<%= @user.user_profile.family_name_sub %><%= @user.user_profile.last_name_sub %></p>
  <p>氏　　名：<%= @user.user_profile.family_name %><%= @user.user_profile.last_name %></p>
  <p>お誕生日：<%= @user.user_profile.family_name_sub %><%= @user.user_profile.last_name_sub %></p>
  <p>〒：<%= @user.user_profile.add_no %></p>
  <p>都道府県：<%= @user.user_profile.prefectures %></p>
  <p>住所：<%= @user.user_profile.address %></p>
  <p>ご連絡先１：<%= @user.user_profile.phone_no1 %></p>
  <p>ご連絡先２：<%= @user.user_profile.phone_no2 %></p>

  <p>実務経験：<%= @user.artisan_profile.workexp %></p>
  <p>家庭縫製経験： <%= @user.artisan_profile.homeworkexp %></p>
  <p>経験年数：<%= @user.artisan_profile.skill_exp %></p>
  <p>スキル：<%= @user.artisan_profile.skill %></p>
  <p>スキル詳細：<%= @user.artisan_profile.skill_free %></p>
  <p>ジャンル：<%= @user.artisan_profile.genre %><p>
  <p>ジャンル詳細：<%= @user.artisan_profile.genre_free %><p>
  <p>アイテム：<%= @user.artisan_profile.item %></p>
  <p>得意アイテム：<%= @user.artisan_profile.item_free %></p>
  <p>設備：<%= @user.artisan_profile.facillity %></p>
  <p>その他設備：<%= @user.artisan_profile.facillity_free %></p>
  <p>【加工設備】：<%= @user.artisan_profile.workexp_text %></p>
  <p>経歴詳細：<%= @user.artisan_profile.workexp_text %></p>
  <p>自己PR：<%= @user.artisan_profile.mypr %></p>
  <p>自己紹介：<%= @user.artisan_profile.myprofile %></p>
  <p>お仕事状況：<%= @user.artisan_profile.work_status %></p>

  <%= link_to 'プロフィール登録', edit_user_profile_path(@user.id), class: "btn btn-info" %>
  <%= link_to '職人申請', edit_artisan_profile_path(@user.id), class: "btn btn-info" %>
  <%= link_to 'ユーザーを削除する', user_path(@user.id), class: "btn btn-info", method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
  
</div>

app/views/artisan_profiles/index.html.erb
<main class="artisans-page">
  <div class="row artisans-page__header">
    <h1 class="col-12 artisans-page__title">職人一覧</h1>
  </div>
  <div class="col-12 artisans-page__header2">
    <%= render "layouts/sort_bar" %>
  </div>
  <div class="row col-12 col-md-10 col-lg-11 col-xl-10 artisan-list__wrap">
    <div class="row col-12 artisan-list_void"></div>
    <% @artisans.each do |artisan| %>
      <div class=" col-9 col-sm-8 col-md-5 col-lg-3 artisan-list">
        <div class="row">
          <p class="col-11 artisan-list__image"><%= image_tag artisan.artisan_profile.artisan_image.to_s %></p>
        </div>
        <div class="row">
          <p class="artisan-list__title"></p>
        </div>
        <div class="row">
          <p class="col-4 artisan-list__image2"><%= image_tag artisan.image.to_s %></p>
        </div>
        <div class="row">
          <p class="col-12 artisan-list__year">実務経験&ensp;<%= artisan.artisan_profile.workexp %></p>
        </div>
        <div class="row">
          <p class="col-12 artisan-list__name"><%= artisan.user_profile.family_name %>&ensp;<%= artisan.user_profile.last_name %></p>
        </div>
        <div class="row">
          <p class="col-12 artisan-list__pr"><%= artisan.artisan_profile.mypr %></p>
        </div>
        <div>
          <p class="col-12 artisan-list__pr"><%= artisan.artisan_profile.work_status %></p>
        </div>
        <div>
          <%= link_to '詳細', artisan_profile_path(artisan) %>
        </div>
        <div class="row artisan-list__bar"></div>
      </div>
    <% end %>
    <div class="row col-12 artisan-list_void"></div>
  </div>
</main>

app/views/artisan_profiles/show.html.erb
<main class="show-artisan-page">
  <h1 class="show-artisan-page__title">職人紹介</h1>
  <div class="row show-artisan1">
    <div class="col-md-4">
      <div class="col-10 col-sm-8 col-md-12 col-lg-10 col-xl-8 show-artisan1__image__wrap">
        <p class="show-artisan1__image__decoration"><span class="show-artisan1__image__decoration__content"><%= @artisan_profile.workexp %></span>年</p>
        <p class="show-artisan1__image"><%= @artisan_profile.artisan_image.to_s %></p>
        <p class="col-12 show-artisan1__image__decoration2"><%= @user_profile.family_name %>&ensp;<%= @user_profile.last_name %></p>
      </div>
    </div>

    <div class="col-md-8 col-lg-7 show-artisan1__wrap">
      <div class="row show-artisan1__content__wrap">
        <p class="col-md-2"></p>
        <div class="col-md-10">
          <p class="show-artisan1__content_sm"><%= @user_profile.family_name_sub %>&ensp;<%= @user_profile.last_name_sub %></p>
        </div>
      </div>

      <div class="row show-artisan1__content__wrap2">
        <p class="col-md-3 col-lg-2 show-artisan1__title">名&emsp;前</p>
        <div class="col-md-9 col-lg-10">
          <p class="show-artisan1__content_sm2"><%= @user_profile.family_name_sub %>&ensp;<%= @user_profile.last_name_sub %></p>
          <p class="show-artisan1__content2"><%= @user_profile.family_name %>&ensp;<%= @user_profile.last_name %></p>
        </div>
      </div>

      <div class="row show-artisan1__content__wrap3">
        <p class="col-md-3 col-lg-2 show-artisan1__title">ジャンル</p>
        <div class="col-md-9 col-lg-10">
          <% @artisan_genres.each do |genre| %>
            <p class="col-5 col-md-5 col-lg-4 show-artisan1__content3"><%= genre %></p>
          <% end %>
        </div>
      </div>

      <div class="row show-artisan1__content__wrap3">
        <p class="col-md-3 col-lg-2 show-artisan1__title">設備</p>
        <div class="col-md-9 col-lg-10">
          <% @artisan_facillities.each do |facillity| %>
            <p class="col-md-5 col-lg-5 col-xl-4 show-artisan1__content3"><%= facillity %></p>
          <% end %>
        </div>
      </div>

      <div class="row show-artisan1__content__wrap3">
        <p class="col-md-3 col-lg-2 show-artisan1__title">アイテム</p>
        <div class="col-md-9 col-lg-10">
          <% @artisan_items.each do |item| %>
            <p class="col-5 col-lg-3 col-xl-2 show-artisan1__content3"><%= item %></p>
          <% end %>
        </div>
      </div>

      <div class="row show-artisan1__content__wrap3">
        <p class="col-md-3 col-lg-2 show-artisan1__title">スキル</p>
        <div class="col-md-9 col-lg-10">
          <p class="col-md-5 col-lg-3 col-xl-2 show-artisan1__content3 show-artisan1__content4 show-artisan1__content4_sm"><%= @artisan_profile.skill %></p>
          <p class="col-md-5 col-lg-3 col-xl-2 show-artisan1__content5">スキル年数</p>
          <p class="col-md-5 col-lg-3 col-xl-2 show-artisan1__content3 show-artisan1__content4"><%= @artisan_profile.skill_exp %>年</p>
        </div>
      </div>

      <div class="row show-artisan1__content__wrap3">
        <p class="col-md-3 col-lg-2"></p>
        <div class="col-md-9 col-lg-10">
          <p class="col-md-9 col-lg-10 show-artisan1__content6"><%= @artisan_profile.skill_free %></p>
          <% if @user.id == current_user.id%>
            <p><%= link_to "職人情報を編集する", edit_artisan_profile_path(current_user.id), class: "edit-artisan__link" %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row show-artisan2">
    <p class="col-md-3 show-artisan2__title">経歴紹介</p>
    <p class="col-11 col-md-7 show-artisan2__content"><%= @artisan_profile.workexp_text %></p>
    <p class="col-md-3 show-artisan2__title">自己PR</p>
    <p class="col-11 col-md-7 show-artisan2__content"><%= @artisan_profile.mypr %></p>
    <p class="col-md-3 show-artisan2__title">自己紹介</p>
    <p class="col-11 col-md-7 show-artisan2__content"><%= @artisan_profile.myprofile %></p>
  </div>

</main>