config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "tops#index"
  resources :users, :user_profiles do
    resources :user_comments, only: %i[create destroy]
  end
  resources :artisan_profiles, only: %i[index show edit update]
  resources :sessions, only: %i[new create destroy]
  resources :project_likes, only: %i[index create destroy]
  resources :relationships, only: %i[index create destroy]
  resources :ideas do
    resources :idea_comments, only: %i[create destroy]
    resources :conversations do
      resources :messages
    end
  end
  post 'projects/:id', to: 'project_returns#create'
  resources :projects do
    resources :comments, only: %i[create destroy]
  end
  # resources :conversations do
  #   resources :messages
  # end
  get 'agreements/terms_of_service'
  get 'agreements/privacy_policy'
  get 'agreements/product_team'
  resources :sponsor_lists, only: [:create]
  resources :coming_soons, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :new
  validates :name,  presence: true, length: { maximum: 30 }
  before_validation { email.downcase! }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_one :user_profile, inverse_of: :user, dependent: :destroy
  accepts_nested_attributes_for :user_profile, reject_if: :all_blank, update_only: true
  has_one :artisan_profile, inverse_of: :user, dependent: :destroy
  accepts_nested_attributes_for :artisan_profile, reject_if: :all_blank
  has_many :comments
  has_many :projects
  has_many :idea_comments, dependent: :destroy
  has_many :project_likes, dependent: :destroy
  has_many :like_projects, through: :project_likes, source: :project

  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :ideas, dependent: :destroy
  has_many :sponsor_lists, dependent: :destroy
  has_many :user_comments, dependent: :destroy

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: %i[index show]
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authenticate_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
    if logged_in?
      redirect_to root_path, notice: "ログインしています。"
    end
  end

  def create
    @user = User.new(user_params)
    @user.build_user_profile(user_profile_params)
    @user.build_artisan_profile(artisan_profile_params)
    if params[:back]
      render :new
    else
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user.id), notice: "ユーザーを登録しました。"
      else
        flash.now[:alert] = "ユーザー登録に失敗しました。"
        render :new
      end
    end
  end

  def show
    @ideas = Idea.all
    @user_comments = @user.user_comments
    @user_comment = @user.user_comments.build
  end

  def edit
    flash[:notice] = 'ユーザー編集'
    @user_profile = @user.user_profile
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ユーザーを更新しました。"
    else
      flash.now[:alert] = "更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: "ユーザーを削除しました。"
  end

  def confirm
    @user = User.new(user_params)
    # @user.image_user.cache!#carriewave設定
    render :new if @user.invalid?
  end

  def favorite
    @user = User.find(params[:id])
    @favorites = @user.favorites
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :image,
      :image_cache
    )
  end

  def user_edit_params
    params.require(:user).permit(
      :name,
      :email,
      :image_name,
      :image_cache,
      user_profile_attributes:[
        :family_name,
        :family_name_sub,
        :last_name,
        :last_name_sub,
        :sex,
        :birthday,
        :add_no,
        :prefectures,
        :address,
        :phone_no1,
        :phone_no2
      ]
    )
  end

  def user_profile_params
    params.require(:user).permit(
        :family_name, 
        :family_name_sub,
        :last_name,
        :last_name_sub,
        :sex,
        :birthday,
        :add_no,
        :prefectures,
        :address,
        :phone_no1,
        :phone_no2
    )
  end

  def artisan_profile_params
    params.require(:user).permit(
        :workexp,
        :homeworkexp,
        :skill,
        :skill_free,
        :skill_exp,
        :genre,
        :genre_free,
        :item,
        :item_free,
        :facillity,
        :facillity_free,
        :workexp_text,
        :mypr,
        :myprofile,
        :work_status
      )
  end

  def authenticate_user
    unless current_user.id == @user.id
      redirect_to root_path, alert: "権限がありません。"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div class="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id))do |f| %>
      <%= f.hidden_field :followed_id %>
      <p class="show-menu__follow"><%= svg("user-plus-solid.svg", class: "show-menu__follow-icon") %>&thinsp;<%= f.submit "このプロジェクトのオーナーをフォロー", class: "show-menu__follow__button" %></p>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete) do |f| %>
      <p class="show-menu__follow"><%= svg("user-plus-solid.svg", class: "show-menu__follow-icon") %>&thinsp;<%= f.submit "プロジェクトオーナーのフォローを解除", class: "show-menu__follow__button2" %></p>
    <% end %>
  <% end %>
</div>

app/views/users/_follow_form2.html.erb
<div class="follow_form2_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id))do |f| %>
      <%= f.hidden_field :followed_id %>
      <p class="show-menu__follow"><%= svg("user-plus-solid.svg", class: "show-menu__follow-icon") %>&thinsp;<%= f.submit "このプロジェクトのオーナーをフォロー", class: "show-menu__follow__button" %></p>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete) do |f| %>
      <p class="show-menu__follow"><%= svg("user-plus-solid.svg", class: "show-menu__follow-icon") %>&thinsp;<%= f.submit "プロジェクトオーナーのフォローを解除", class: "show-menu__follow__button2" %></p>
    <% end %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, url: user_path, local: true, method: :patch) do |f| %>
  <div class="row">
    <div class="col-md-4 order-md-1 mb-4">
      <strong>Image:</strong>
      <%= image_tag @user.image.to_s %>
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted"><%= @user.name %></span>
      </h4>
      <ul class="list-group mb-3">
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">アイディア一覧</h6>
            <small class="text-muted">投稿したアイディアの管理</small>
            
          </div>
          <span class="text-muted"></span>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">メッセージ一覧</h6>
            <small class="text-muted">メッセージはこまめにCheck！</small>
          </div>
          <span class="text-muted"></span>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">お支払い・売り上げ管理</h6>
            <small class="text-muted">口座登録・振り込み申請などもコチラ</small>
          </div>
          <span class="text-muted"></span>
        </li>
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">会員情報・変更</h6>
            <small>EXAMPLECODE</small>
          </div>
          <span class="text-success"></span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span></span>
          <strong></strong>
        </li>
      </ul>
    </div>

    <%= f.fields_for :user_profile do |a| %>
      <div class="col-md-8 order-md-2">
        <h4 class="mb-3">プロフィール</h4>
        
        <div class="row">
          <div class="col-md-6 mb-3">
            <%= a.label :family_name %>
            <%= a.text_field :family_name, class: "form-control", id: "firstName", placeholder: "例）山田", value: @user.user_profile.family_name, readonly: true %>
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="lastName">Last name</label>
            <%= a.text_field :last_name, class: "form-control", id: "lastName", placeholder: "例）太郎", value: @user.user_profile.last_name, readonly: true %>
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="firstNameSub">First name</label>
            <%= a.text_field :family_name_sub, class: "form-control", id: "firstName", placeholder: "例）やまだ", value: @user.user_profile.family_name_sub, readonly: true %>

            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="lastName">Last name</label>
            <%= a.text_field :last_name_sub, class: "form-control", id: "lastName", placeholder: "例）たろう", value: @user.user_profile.last_name_sub, readonly: true  %>
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-3">
            <%= a.label :add_no %>
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text">〒</span>
              </div>
              <%= a.text_field :add_no, class: "form-control", id: "AddNumber", placeholder: "例）000-0000", value: @user.user_profile.add_no, readonly: true %>
              <div class="invalid-feedback" style="width: 100%;">
                Your username is required.
              </div>
            </div>
          </div>
                        
          <div class="col-md-6 mb-3">
            <%= a.label :prefectures %>
            <%= a.text_field :prefectures, class: "form-control", id: "Prefectures", placeholder: "例）東京都", value: @user.user_profile.prefectures, readonly: true %>
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>

        <div class="mb-3">
          <%= a.label :address %>
          <%= a.text_field :address, class: "form-control", id: "address", placeholder: "建物名までご記入ください", value: @user.user_profile.address, readonly: true %>
          <div class="invalid-feedback">
            Please enter your shipping address.
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-3">
            <%= a.label :phone_no1 %>
            <%= a.text_field :phone_no1, class: "form-control", id: "PhoneNumber1", placeholder: "例）00000000000(ハイフン不要)", value: @user.user_profile.phone_no1, readonly: true %>
            <div class="invalid-feedback" style="width: 100%;">
              Your username is required.
            </div>
          </div>
                        
          <div class="col-md-6 mb-3">
            <%= a.label :phone_no2 %>
            <%= a.text_field :phone_no2, class: "form-control", id: "PhoneNumber2", placeholder: "例）00000000000(ハイフン不要)", value: @user.user_profile.phone_no2, readonly: true %>
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>

        <div class="mb-3">
          <%= link_to 'プロフィール編集', edit_user_profile_path(@user.id), class: "btn btn-primary btn-lg btn-block mt-5" %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/_form_status.html copy.erb
<strong>Image:</strong>
<%= image_tag @user.image.to_s %>
<h4 class="d-flex justify-content-between align-items-center mb-3">
  <span class="text-muted"><%= @user.name %></span>
</h4>
<ul class="list-group mb-3">
  <li class="list-group-item d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">アイディア一覧</h6>
      <small class="text-muted">投稿したアイディアの管理</small>
    </div>
    <span class="text-muted"></span>
  </li>
  <li class="list-group-item d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">メッセージ一覧</h6>
      <small class="text-muted">メッセージはこまめにCheck！</small>
    </div>
    <span class="text-muted"></span>
  </li>
  <li class="list-group-item d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">お支払い・売り上げ管理</h6>
      <small class="text-muted">口座登録・振り込み申請などもコチラ</small>
    </div>
    <span class="text-muted"></span>
  </li>
  <li class="list-group-item d-flex justify-content-between bg-light">
    <div class="text-success">
      <h6 class="my-0">会員情報・変更</h6>
      <small>EXAMPLECODE</small>
    </div>
    <span class="text-success"></span>
  </li>
  <li class="list-group-item d-flex justify-content-between">
    <span></span>
    <strong></strong>
  </li>
</ul>

app/views/users/_new.html.erb
<div class="container">
  <h1>Sign up</h1>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with(model: @user, local: true) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "ユーザー登録する", class: "btn btn-info" %>
  <% end %>
</div>
<div class="container">

app/views/users/_read.html.erb
<main class="container-fluid my-page">
  <h1 class="row col-12 col-lg-10 my-page__title">会員情報・住所確認/変更</h1>
  <div class="row">
    <%= render "layouts/profile_menu" %>
    <section class="col-10 col-md-6 offset-1 offset-md-0 my-page__form">
      <%= form_with(model: @user, url: user_path, local: true, method: :patch) do |f| %>
        <%= f.fields_for :user_profile do |a| %>
          <div class="row">
            <div class="col-md-6 mb-3">
              <%= a.label :family_name %>
              <%= a.text_field :family_name, class: "form-control my-page__form__input", placeholder: "例）山田", value: @user.user_profile.family_name, readonly: true %>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <%= a.label :last_name %>
              <%= a.text_field :last_name, class: "form-control my-page__form__input", placeholder: "例）太郎", value: @user.user_profile.last_name, readonly: true %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <%= a.label :family_name_sub %>
              <%= a.text_field :family_name_sub, class: "form-control my-page__form__input", placeholder: "例）やまだ", value: @user.user_profile.family_name_sub, readonly: true %>

              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <%= a.label :last_name_sub %>
              <%= a.text_field :last_name_sub, class: "form-control my-page__form__input", placeholder: "例）たろう", value: @user.user_profile.last_name_sub, readonly: true  %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <%= a.label :add_no %>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">〒</span>
                </div>
                <%= a.text_field :add_no, class: "form-control my-page__form__input", placeholder: "例）000-0000", value: @user.user_profile.add_no, readonly: true %>
                <div class="invalid-feedback" style="width: 100%;">
                  Your username is required.
                </div>
              </div>
            </div>

            <div class="col-md-6 mb-3">
              <%= a.label :prefectures %>
              <%= a.text_field :prefectures, class: "form-control my-page__form__input", placeholder: "例）東京都", value: @user.user_profile.prefectures, readonly: true %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>

          <div class="mb-3">
            <%= a.label :address %>
            <%= a.text_field :address, class: "form-control my-page__form__input",  placeholder: "建物名までご記入ください", value: @user.user_profile.address, readonly: true %>
            <div class="invalid-feedback">
              Please enter your shipping address.
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <%= a.label :phone_no1 %>
              <%= a.text_field :phone_no1, class: "form-control my-page__form__input", placeholder: "例）00000000000(ハイフン不要)", value: @user.user_profile.phone_no1, readonly: true %>
              <div class="invalid-feedback" style="width: 100%;">
                Your username is required.
              </div>
            </div>

            <div class="col-md-6 mb-3">
              <%= a.label :phone_no2 %>
              <%= a.text_field :phone_no2, class: "form-control my-page__form__input", placeholder: "例）00000000000(ハイフン不要)", value: @user.user_profile.phone_no2, readonly: true %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>
          <div class="mb-3 my-page__form__button__wrap">
            <%= link_to "職人登録申請フォームへ", edit_artisan_profile_path(@user.id), class: "btn btn-info form-control my-page__form__button" %>
          </div>
        <% end %>
      <% end %>
      <div class="mb-3">
        <div id="user_comments_area">
          <%= render partial: 'user_comments/index', locals: { user_comment: @user_comment, user: @user } %>
        </div>
        <%= form_with(model: [@user, @user_comment], url: user_user_comments_path(user_id: @user.id), remote: true ) do |form| %>
          <div class="field mb-3">
            <%= form.text_area :content, class: "col-lg-12 btn show-idea-comment__button form-control" %>
          </div>
          <%= hidden_field :comment_user_id, value: current_user.id %>
          <div class="actions"><%= form.submit "コメントする", class: "col-lg-12 btn btn-warning show-idea-comment__button" %></div>
        <% end %>
      </div>
    </section>
  </div>
</main>

app/views/users/_show.html.erb
<div class="container">
  <p>
  <strong>Image:</strong>
  <%= image_tag @user.image.to_s %>
  </p>
  <h1>user詳細画面</h1>
  <p>ニックネーム：<%= @user.name %></p>
  <p>登録メール：<%= @user.email %></p>
  
  <p>ふりがな：<%= @user.user_profile.family_name_sub %><%= @user.user_profile.last_name_sub %></p>
  <p>氏　　名：<%= @user.user_profile.family_name %><%= @user.user_profile.last_name %></p>
  <p>お誕生日：<%= @user.user_profile.family_name_sub %><%= @user.user_profile.last_name_sub %></p>
  <p>〒：<%= @user.user_profile.add_no %><p>都道府県：<%= @user.user_profile.prefectures %></p>
  <p>住所：<%= @user.user_profile.address %></p>
  <p>ご連絡先１：<%= @user.user_profile.phone_no1 %></p>
  <p>ご連絡先２：<%= @user.user_profile.phone_no2 %></p>

  <%= link_to 'プロフィール登録', edit_user_profile_path(@user.id), class: "btn btn-info" %>
  <%= link_to '職人申請', edit_artisan_profile_path(@user.id), class: "btn btn-info" %>
  <%= link_to 'ユーザーを削除する', user_path(@user.id), class: "btn btn-info", method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
  
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="py-5 text-center">
    <h2></h2>
    <p class="lead"></p>
  </div>
  <%= form_with(model: @user, url: user_path, local: true, method: :patch) do |f| %>
    <div class="row">
      <div class="col-md-4 order-md-1 mb-4">
        <%= image_tag @user.image.to_s, class: "col-md-12" %>
        <%= f.file_field :image, class: "col-md-12" %>
        <h4 class="d-flex justify-content-between align-items-center mb-3 col-md-12">
          <%= f.text_field :name, class: "col-md-12" %>
        </h4>
      </div>


      <div class="col-md-8 order-md-1" >
        <%= f.fields_for :user_profile do |a| %>
          <h4 class="mb-3">ユーザー情報</h4>

          <div class="row">
            <div class="col-md-6 mb-3">
              <%= a.label :family_name %>
              <%= a.text_field :family_name, class: "form-control", id: "firstName", placeholder: "例）山田", readonly: true  %>
            </div>
            <div class="col-md-6 mb-3">
              <label for="lastName">Last name</label>
              <%= a.text_field :last_name, class: "form-control", id: "lastName", placeholder: "例）太郎", readonly: true  %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <label for="firstNameSub">First name</label>
              <%= a.text_field :family_name_sub, class: "form-control", id: "firstName", placeholder: "例）やまだ", readonly: true %>
            </div>
            <div class="col-md-6 mb-3">
              <label for="lastName">Last name</label>
              <%= a.text_field :last_name_sub, class: "form-control", id: "lastName", placeholder: "例）たろう", readonly: true  %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <%= a.label :add_no %>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">〒</span>
                </div>
                <%= a.text_field :add_no, class: "form-control", id: "AddNumber", placeholder: "例）0000000（ハイフン不要）", readonly: true %>
              </div>
            </div>

            <div class="col-md-6 mb-3">
              <%= a.label :prefectures %>
              <%= a.text_field :prefectures, class: "form-control", id: "Prefectures", placeholder: "例）東京都", readonly: true %>
            </div>
          </div>

          <div class="mb-3">
            <%= a.label :address %>
            <%= a.text_field :address, class: "form-control", id: "address", placeholder: "建物名までご記入ください", readonly: true %>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <%= a.label :phone_no1 %>
              <%= a.text_field :phone_no1, class: "form-control", id: "PhoneNumber1", placeholder: "例）00000000000(ハイフン不要)", readonly: true %>
            </div>

            <div class="col-md-6 mb-3">
              <%= a.label :phone_no2 %>
              <%= a.text_field :phone_no2, class: "form-control", id: "PhoneNumber2", placeholder: "例）00000000000(ハイフン不要)", readonly: true %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <%= f.submit :"登録する", class: "btn btn-primary btn-lg btn-block mt-5" %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>user一覧</h1>
  <table>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
    </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to '詳細を見る', user_path(user.id) %></td>
      <td><%= link_to 'プロフィール登録', edit_user_profile_path(user.id) %></td>
      <td><%= link_to '削除', user_path(user.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
      <td><%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %></td>
    </tr>
    
  <% end %>
  </table>
</div>

app/views/users/new.html.erb
<main class="container-fluid signup-page">
  <div class="signup">
    <div class="row">
      <h1 class="col-11 col-sm-8 col-md-7 col-lg-6 col-xl-5 signup__title">ブランドファンディングはあなたのやりたい事を応援します。仲間と一緒にアイディアをカタチに</h1>
    </div>
    <div class="signup-form">
      <%= form_with(model: @user, local: true) do |f| %>
        <% if @user.errors.any? %>
          <% @user.errors.full_messages.each do |message| %>
            <ul>
              <li class="col-12 col-sm-8 col-md-5 col-lg-4 col-xl-3 signup__list">
                <%= svg("exclamation-circle-solid.svg", class: "signup__list__icon") %>
                <%= message %>
              </li>
            </ul>
          <% end %>
        <% end %>
        <p class="col-11 col-sm-8 col-md-7 col-lg-6 col-xl-5 signup-form__wrap"><%= f.text_field :name, class:"form-control signup-form__input", placeholder: "ニックネーム" %></p>
        <p class="col-11 col-sm-8 col-md-7 col-lg-6 col-xl-5 signup-form__wrap"><%= f.email_field :email, class:"form-control signup-form__input", placeholder: "メールアドレス" %></p>
        <p class="col-11 col-sm-8 col-md-7 col-lg-6 col-xl-5 signup-form__wrap"><%= f.password_field :password, class:"form-control signup-form__input", placeholder: "パスワード" %></p>
        <p class="col-11 col-sm-8 col-md-7 col-lg-6 col-xl-5 signup-form__wrap"><%= f.password_field :password_confirmation, class:"form-control signup-form__input", placeholder: "パスワード確認用" %></p>
        <p class="col-12 col-sm-7 offset-3 signup-form__about">登録は無料。年会費もかかりません。</p>

        <p class="col-12 col-sm-7 signup-form__privacy">「登録」のボタンを押すことにより、
          <%= link_to "利用規約", agreements_terms_of_service_path, class: "signup-form__terms" %>、
          <%= link_to "プライバシーポリシー", agreements_privacy_policy_path, class: "signup-form__privacy2" %>に同意したとみなします。
        </p>
        <p class="col-9 col-sm-6 col-lg-4 col-xl-3 signup-form__button__wrap"><%= f.submit "登録", class: "col-12 btn signup-form__button" %></p>
      <% end %>
      <%= form_with(scope: :session, url: sessions_path, local: true) do |f| %>
        <%= f.hidden_field :email, value: 'test1@example.com' %>
        <%= f.hidden_field :password, value: '123456' %>
        <p class="col-9 col-sm-5 col-md-4 col-lg-3 signup-form__button__wrap">
          <%= f.submit "テストユーザー1でログイン", class: "col-12 btn signup-form__button" %>
        </p>
      <% end %>
      <%= form_with(scope: :session, url: sessions_path, local: true) do |f| %>
        <%= f.hidden_field :email, value: 'test2@example.com' %>
        <%= f.hidden_field :password, value: '123456' %>
        <p class="col-9 col-sm-5 col-md-4 col-lg-3 signup-form__button__wrap">
          <%= f.submit "テストユーザー2でログイン", class: "col-12 btn signup-form__button" %>
        </p>
      <% end %>
      <%= form_with(scope: :session, url: sessions_path, local: true) do |f| %>
        <%= f.hidden_field :email, value: 'test3@example.com' %>
        <%= f.hidden_field :password, value: '123456' %>
        <p class="col-9 col-sm-5 col-md-4 col-lg-3 signup-form__button__wrap">
          <%= f.submit "テストユーザー3でログイン", class: "col-12 btn signup-form__button" %>
        </p>
      <% end %>
    </div>
  </div>
</main>

app/views/users/show.html.erb
  <%= render 'read', user: @user %>