config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "tops#index"
  resources :users, :user_profiles do
    resources :user_comments, only: %i[create destroy]
  end
  resources :artisan_profiles, only: %i[index show edit update]
  resources :sessions, only: %i[new create destroy]
  resources :project_likes, only: %i[index create destroy]
  resources :relationships, only: %i[index create destroy]
  resources :ideas do
    resources :idea_comments, only: %i[create destroy]
    resources :conversations do
      resources :messages
    end
  end
  post 'projects/:id', to: 'project_returns#create'
  resources :projects do
    resources :comments, only: %i[create destroy]
  end
  # resources :conversations do
  #   resources :messages
  # end
  get 'agreements/terms_of_service'
  get 'agreements/privacy_policy'
  get 'agreements/product_team'
  resources :sponsor_lists, only: [:create]
  resources :coming_soons, only: [:index]
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  has_many :user_comments, dependent: :destroy
  belongs_to :user, inverse_of: :user_profile
  validates :password, presence: true, length: { minimum: 6 }, on: :new
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController

  def edit
    @user = User.find(params[:id])
    @user_profile = @user.user_profile
  end

  def update
    flash[:notice] = '更新'
    @user = User.find(params[:id])
    if @user.user_profile.update(user_profile_params)
      redirect_to user_path(@user.id), notice: "プロフィールを更新しました。"
    else
      flash.now[:alert] = "更新に失敗しました。"
      render :edit
    end
  end

  private

  def user_profile_params
    params.require(:user_profile).permit(
        :family_name,
        :family_name_sub,
        :last_name,
        :last_name_sub,
        :sex,
        :birthday,
        :add_no,
        :prefectures,
        :address,
        :phone_no1,
        :phone_no2
      )
  end

end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_edit.html.erb
<div class="container">
  <h1>プロフィール</h1>
  <%= form_with(model: @user_profile, url: user_profile_path, local: true, method: :patch) do |a| %>
      <table>
      <h3>プロフィール編集</h3>
      <tr><td><% a.label :family_name %></td></tr>
      <tr><td><%= a.text_field :family_name , placeholder: :family_name %></td></tr>
      <tr><td><% a.label :last_name %></td></tr>
      <tr><td><%= a.text_field :last_name, placeholder: :last_name %></td></tr>
      <tr><td><% a.label :family_name_sub %></td></tr>
      <tr><td><%= a.text_field :family_name_sub, placeholder: :family_name_sub %></td></tr>
      <tr><td><% a.label :last_name_sub %></td></tr>
      <tr><td><%= a.text_field :last_name_sub, placeholder: :last_name_sub %></td></tr>
      <tr><td><% a.label :birthday %></td></tr>
      <tr><td><%= a.text_field :birthday, placeholder: :birthday %></td></tr>
      <tr><td><% a.label :add_no %></td></tr>
      <tr><td><%= a.number_field :add_no, placeholder: :add_no %></td></tr>
      <tr><td><% a.label :prefectures %></td></tr>
      <tr><td><%= a.text_field :prefectures, placeholder: :address %></td></tr>
      <tr><td><% a.label :address %></td></tr>
      <tr><td><%= a.text_field :address, placeholder: :address %></td></tr>
      <tr><td><% a.label :phone_no1 %></td></tr>
      <tr><td><%= a.number_field :phone_no1, placeholder: :phone_no1 %></td></tr>
      <tr><td><% a.label :phone_no2 %></td></tr>
      <tr><td><%= a.number_field :phone_no2, placeholder: :phone_no2 %></td></tr>
      </table>
    <%= a.submit :"ユーザー登録する", class: "btn btn-info", method: :patch %>
  <% end %>
</div>

app/views/user_profiles/edit.html.erb
<main class="container-fluid my-page">
  <h1 class="row col-12 col-lg-10 my-page__title">会員情報・住所確認/変更</h1>
  <div class="row">

    <%= render "layouts/profile_menu" %>

    <section class="col-10 col-md-6 offset-1 offset-md-0 my-page__form">
      <%= form_with(model: @user_profile, url: user_profile_path, local: true, method: :patch) do |f| %>
        <div class="row">
          <div class="col-md-6 mb-3">
            <%= f.label :family_name %>
            <%= f.text_field :family_name, class: "form-control my-page__form__input", placeholder: "例）山田"  %>

            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: "form-control my-page__form__input", placeholder: "例）太郎"  %>
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-3">
            <%= f.label :family_name_sub %>
            <%= f.text_field :family_name_sub, class: "form-control my-page__form__input", placeholder: "例）やまだ" %>

            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <%= f.label :last_name_sub %>
            <%= f.text_field :last_name_sub, class: "form-control my-page__form__input", placeholder: "例）たろう"  %>
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-3">
            <%= f.label :add_no %>
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text">〒</span>
              </div>
              <%= f.text_field :add_no, class: "form-control my-page__form__input", placeholder: "例）000-0000" %>
              <div class="invalid-feedback" style="width: 100%;">
                Your username is required.
              </div>
            </div>
          </div>

          <div class="col-md-6 mb-3">
            <%= f.label :prefectures %>
            <%= f.text_field :prefectures, class: "form-control my-page__form__input", placeholder: "例）東京都" %>
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>

        <div class="mb-3">
          <%= f.label :address %>
          <%= f.text_field :address, class: "form-control my-page__form__input", placeholder: "建物名までご記入ください" %>
          <div class="invalid-feedback">
            Please enter your shipping address.
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-3">
            <%= f.label :phone_no1 %>
            <%= f.text_field :phone_no1, class: "form-control my-page__form__input", placeholder: "例）00000000000(ハイフン不要)" %>
            <div class="invalid-feedback" style="width: 100%;">
              Your username is required.
            </div>
          </div>

          <div class="col-md-6 mb-3">
            <%= f.label :phone_no2 %>
            <%= f.text_field :phone_no2, class: "form-control my-page__form__input", placeholder: "例）00000000000(ハイフン不要)" %>
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>
        <div class="my-page__form__button_wrap">
          <%= f.submit "プロフィールを編集する", class: "btn btn-success btn-lg btn-block mt-3 my-page__form__button" %>
          <%= link_to "戻る", user_path(current_user.id), class: "btn btn-secondary btn-lg btn-block mt-3 my-page__form__button" %>
        </div>

      <% end %>
    </section>
  </div>
</main>

app/views/user_profiles/new.html.erb
<div class="container">
  <div class="py-5 text-center">
    <h2></h2>
    <p class="lead"></p>
  </div>
  <%= form_with(model: @user_profile, url: user_profile_path, local: true, method: :patch) do |f| %>
    <div class="row">
      <div class="col-md-4 order-md-2 mb-4">
        <strong>Image:</strong>
        <%= image_tag @user.image.to_s %>
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted"><%= @user.name %></span>
        </h4>
        <ul class="list-group mb-3">
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">アイディア一覧</h6>
              <small class="text-muted">投稿したアイディアの管理</small>
            </div>
            <span class="text-muted"></span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">メッセージ一覧</h6>
              <small class="text-muted">メッセージはこまめにCheck！</small>
            </div>
            <span class="text-muted"></span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">お支払い・売り上げ管理</h6>
              <small class="text-muted">口座登録・振り込み申請などもコチラ</small>
            </div>
            <span class="text-muted"></span>
          </li>
          <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">会員情報・変更</h6>
              <small>EXAMPLECODE</small>
            </div>
            <span class="text-success"></span>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <span></span>
            <strong></strong>
          </li>
        </ul>
      </div>

      <div class="col-md-8 order-md-1">

          <h4 class="mb-3">ユーザー情報</h4>

          <div class="row">
            <div class="col-md-6 mb-3">
              <%= f.label :family_name %>
              <%= f.text_field :family_name, class: "form-control", id: "firstName", placeholder: "例）山田"  %>

              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <label for="lastName">Last name</label>
              <%= f.text_field :last_name, class: "form-control", id: "lastName", placeholder: "例）太郎"  %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <label for="firstNameSub">First name</label>
              <%= f.text_field :family_name_sub, class: "form-control", id: "firstName", placeholder: "例）やまだ" %>

              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <label for="lastName">Last name</label>
              <%= f.text_field :last_name_sub, class: "form-control", id: "lastName", placeholder: "例）たろう"  %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <%= f.label :add_no %>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">〒</span>
                </div>
                <%= f.text_field :add_no, class: "form-control", id: "AddNumber", placeholder: "例）000-0000" %>
                <div class="invalid-feedback" style="width: 100%;">
                  Your username is required.
                </div>
              </div>
            </div>

            <div class="col-md-6 mb-3">
              <%= f.label :prefectures %>
              <%= f.text_field :prefectures, class: "form-control", id: "Prefectures", placeholder: "例）東京都" %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>

          <div class="mb-3">
            <%= f.label :address %>
            <%= f.text_field :address, class: "form-control", id: "address", placeholder: "建物名までご記入ください" %>
            <div class="invalid-feedback">
              Please enter your shipping address.
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <%= f.label :phone_no1 %>
              <%= f.text_field :phone_no1, class: "form-control", id: "PhoneNumber1", placeholder: "例）00000000000(ハイフン不要)" %>
              <div class="invalid-feedback" style="width: 100%;">
                Your username is required.
              </div>
            </div>

            <div class="col-md-6 mb-3">
              <%= f.label :phone_no2 %>
              <%= f.text_field :phone_no2, class: "form-control", id: "PhoneNumber2", placeholder: "例）00000000000(ハイフン不要)" %>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>
          </div>
      </div>
    </div>
  <%= f.submit :"ユーザー情報を編集する", class: "btn btn-primary btn-lg btn-block" %>
  <% end %>

</div>

app/views/user_profiles/new_profile.html.erb
<div class="container">
  <h1>ユーザープロフィール編集</h1>
  <%= form_with(model: @user, local: true) do |f| %>
    <table>
    <tr><td><%= f.label :name %></td></tr>
    <tr><td><%= f.text_field :name %></td></tr>
    <tr><td><%= f.label :email %></td></tr>
    <tr><td><%= f.email_field :email %></td></tr>
    <tr><td></table>
    <%= f.fields_for :user_profile do |a| %>
      <table>
      <h3>プロフィール編集</h3>
      <tr><td><%= a.label :family_name %></td></tr>
      <tr><td><%= a.text_field :family_name %></td></tr>
      <tr><td><%= a.label :last_name %></td></tr>
      <tr><td><%= a.text_field :last_name %></td></tr>
      <tr><td><%= a.label :family_name_sub %></td></tr>分
      <tr><td><%= a.text_field :family_name_sub %></td></tr>
      <tr><td><%= a.label :last_name_sub %></td></tr>
      <tr><td><%= a.text_field :last_name_sub %></td></tr>
      <tr><td><%= a.label :birthday %></td></tr>
      <tr><td><%= a.text_field :lbirthday %></td></tr>
      <tr><td><%= a.label :add_no %></td></tr>
      <tr><td><%= a.text_field :add_no %></td></tr>
      <tr><td><%= a.label :prefectures %></td></tr>
      <tr><td><%= a.text_field :prefectures %></td></tr>
      <tr><td><%= a.label :phone_no1 %></td></tr>
      <tr><td><%= a.text_field :phone_no1 %></td></tr>
      <tr><td><%= a.label :phone_no2 %></td></tr>
      <tr><td><%= a.text_field :phone_no2 %></td></tr>
      <tr><td><%= a.label :last_name_sub %></td></tr>
      <tr><td><%= a.text_field :last_name_sub %></td></tr>
      <tr><td><%= a.label :created_at %></td></tr>
      <tr><td><%= a.text_field :created_at %></td></tr>
      <tr><td><%= a.label :updated_at %></td></tr>
      <tr><td><%= a.text_field :updated_at %></td></tr>
    <% end %>
    </table>
    <%= f.submit :"ユーザー登録する", class: "btn btn-info", method: "post" %>
  <% end %>
</div>